user = int(input("Pls tell me your age"))
print(f"you are currently 15 years old")
print(f"in 10 years, you will be {user + 10} years old" )
print(f"in 20 years, you will be {user + 20} years old" )
print(f"in 30 years, you will be {user + 30} years old" )
